### ISSUE TITLE
cst2hp not in the repo

### ISSUE THREAD

**Issue by SaulAryehKohn** [jaguirre/radionopy#1]
Can't execute the WidefieldBeams method "paper_polarized_beams.py"...

```
saulkohn@Sauls-MacBook-Pro:~/github/radionopy/WidefieldBeams$ python paper_polarized_beams.py 
Traceback (most recent call last):
  File "paper_polarized_beams.py", line 8, in <module>
    from cst2hp import cst2hp
ImportError: No module named cst2hp
```

This may be due to the call 

```
sys.path.append("/Users/jaguirre/PyModules/MyModules/herapy/beam")
```

Could you add cst2hp into the repo?

**Comment by jaguirre** [comment]
It’s in there now.

James Aguirre
Associate Professor 
Department of Physics and Astronomy 
University of Pennsylvania 
209 South 33rd Street Philadelphia, PA 19104 
(215) 898-9596 (office) 
(215) 898-9646 (lab)
http://www.sas.upenn.edu/~jaguirre/
