### ISSUE TITLE
Unable to run in batch

### ISSUE THREAD

**Issue by SaulAryehKohn** [jaguirre/radionopy#7]
Distributing, for example, multiple night's worth of IONEX data over different nodes, generates I/O Errors. This is due to the `geomag.c` script generating `{input,output}.txt` files as part of its execution, which end up overwriting themselves, or being read at the same time as writing, etc.

What is the best way for us to fix this?

**Comment by SaulAryehKohn** [comment]
@zacharymartinot is the solution for this tested and retired?

**Comment by zacharymartinot** [comment]
Fixed this problem in https://github.com/jaguirre/radionopy/commit/19761c547b0f5561d567026897d81d22784d3461
